### ISSUE TITLE
Windows 11 22631.3085 stopped working

### ISSUE THREAD

**Issue by jurienhamaker** [cdhunt/WindowsAudioDevice-Powershell-Cmdlet#76]
Recently after the new Windows 11 update (22631.3085) with the new [sound panel](https://uploads.jurien.dev/Falcon/NVIDIA_Share_M7MADcwsfQ.png) the `AudioDeviceCmdlets` will not allow me to change devices anymore.

Even with powershell ran as administrator, nothing happends when using `Set-AudioDevice -ID "<id>"` or `Set-AudioDevice -Index <index>`.
Things like `Get-AudioDevice -List` & `Set-AudioDevice -PlaybackVolume <float>` still work. Just setting the device by ID does not work for me anymore.

**Comment by abhinavsix** [comment]
Im having the same issue. Did you manage to find a solution?

**Comment by mefranklin6** [comment]
I am (thankfully) unable to reproduce the issue on the latest Windows 11 Enterprise 23H2 22631.3007.  This version has the same 'new' sound panel that you linked.

I take it you're on 22H2?  Maybe try upgrading to 23H2?

**Comment by jurienhamaker** [comment]
@mefranklin6 22641.3085 was already 23H2

My current system version:

    Edition	Windows 11 Pro
    Version	23H2
    Installed on	‎19/‎02/‎2023
    OS build	22631.3296
    Experience	Windows Feature Experience Pack 1000.22687.1000.0

Still doesn't work

**Comment by mefranklin6** [comment]
Tried it on my home PC which is on the same build as yours, still works.

BTW I'm not a dev on this project, just a user contributing data. My C# skills are not that good ATM to do any meaningful work on this.  Hope you get it working!

Edition	Windows 11 Pro
Version	23H2
Installed on	‎10/‎7/‎2022
OS build	22631.3296
Experience	Windows Feature Experience Pack 1000.22687.1000.0

**Comment by jurienhamaker** [comment]
Moved to a ahk script lol
